### ISSUE TITLE
Support ESLint 2

### ISSUE THREAD

**Issue by Ky6uk** [jonathanKingston/ember-cli-eslint#30] opened 2016-02-22 05:47 UTC
It look like problem with supporting `eslint@^2.0.0`. Can we up eslint version?

**Comment by chriskrycho** [comment] 2016-02-26 22:51
Note: this is blocked by https://github.com/jonathanKingston/broccoli-lint-eslint/pull/9, since it uses `broccoli-lint-eslint` under the hood. Once that updates, this will be able to be updated in straightforward fashion.

**Comment by ehntoo** [comment] 2016-03-06 17:29
ESLint 2 will now be installed if you remove and re-install this package. https://github.com/jonathanKingston/broccoli-lint-eslint/pull/9 has landed, and the dependency here is loosely-enough specified that it'll pull in the new version of broccoli-lint-eslint on a new install.

**Comment by chriskrycho** [comment] 2016-03-06 17:33
Outstanding! I'll do just that on Monday and confirm it behaves as expected in our installation.

**Comment by chriskrycho** [comment] 2016-03-07 14:00
Note for anyone else who runs into this on Ember in the next little bit. If you run into `Error: Cannot find module 'estraverse-fb'`, there's another [upstream issue] affecting the interaction between `babel-eslint` and `eslint` proper, having to do with how Babel does some of the monkey-patching. If you're using `babel-eslint` (as you're likely to be if you're using ESLint and Ember CLI together), you need to do one of the following until the issue is resolved (hopefully this week):

- temporarily `npm install estraverse-fb`
- pin to `"eslint": "~2.2.0"` in your package.json

You'll want to track that [upstream issue] to know when to undo that temporary fix.

[upstream issue]: https://github.com/eslint/eslint/issues/5476

**Comment by chriskrycho** [comment] 2016-03-07 14:19
@jonathanKingston tested and confirmed that (with the above qualifications noted) this is resolved. Please feel free to close!

**Comment by ehntoo** [comment] 2016-03-07 14:26
@chriskrycho - I also ran into the `estraverse-fb` issues last night, and would like to highlight a third option. If your codebase sticks to ES6 and doesn't use any features that the standard eslint parser (Espree) doesn't support, you can stop using `babel-eslint` entirely. :)

**Comment by chriskrycho** [comment] 2016-03-07 14:28
@ehntoo Oh, great point. We're using `babel-eslint` throughout a variety of projects, so not a great fit for us, but a good one in general.

**Comment by ehntoo** [comment] 2016-03-07 16:47
Actually, as I'm dealing with this at work today, it'd be nice if we could get a new release of ember-cli-eslint explicitly pulling the new broccoli filter in so I can stop nuking this manually.

@jonathanKingston - is there anything I can help with to get a new release out?

**Comment by chriskrycho** [comment] 2016-03-14 16:59
Update on the `estraverse-fb` issue: it *should* be resolved as of `eslint@2.4.0`, so the underlying problem with `babel-eslint` should go away, I believe.

**Comment by alexlafroscia** [comment] 2016-03-18 15:39
I was able to avoid the `estraverse-fb` issue by installing `babel-eslint@6.0.0-beta.6`

**Closed** 2016-03-22 00:10 UTC

**Comment by BrianSipple** [comment] 2016-03-22 00:12
Closed after https://github.com/jonathanKingston/broccoli-lint-eslint/pull/28
